# Generated by Django 5.2 on 2025-04-22 15:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_groupinvite_expires_at_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinvite',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 24, 15, 32, 0, 970556, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='media',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 21, 32, 0, 967242, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encryption', models.TextField()),
                ('decryption', models.TextField()),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.media')),
            ],
        ),
    ]
