# Generated by Django 5.2 on 2025-04-22 15:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_groupinvite_expires_at_alter_media_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinvite',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 24, 15, 35, 49, 959983, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='media',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 21, 35, 49, 956706, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='OneTimeKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.media')),
            ],
        ),
        migrations.CreateModel(
            name='PreviewLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2025, 4, 22, 21, 35, 49, 960471, tzinfo=datetime.timezone.utc))),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.media')),
            ],
        ),
    ]
