# Generated by Django 5.2 on 2025-04-23 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_groupinvite_expires_at_alter_media_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterField(
            model_name='groupinvite',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 25, 21, 16, 54, 657860, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='media',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 24, 3, 16, 54, 654528, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='previewlink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 24, 3, 16, 54, 658349, tzinfo=datetime.timezone.utc)),
        ),
    ]
