# Generated by Django 5.2 on 2025-04-23 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_group_options_alter_groupinvite_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AddField(
            model_name='key',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 23, 21, 22, 51, 756353, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='key',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='groupinvite',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 25, 21, 22, 27, 69078, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='media',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 24, 3, 22, 27, 67035, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='previewlink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 24, 3, 22, 27, 69358, tzinfo=datetime.timezone.utc)),
        ),
    ]
