# Generated by Django 5.2 on 2025-04-23 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_group_options_key_created_at_key_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinvite',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 25, 21, 49, 31, 984179, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='media',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 24, 3, 49, 31, 982214, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='previewlink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 24, 3, 49, 31, 984458, tzinfo=datetime.timezone.utc)),
        ),
    ]
