# Generated by Django 5.2.1 on 2025-05-12 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_groupinvite_expires_at_alter_media_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='key',
            field=models.CharField(default='dshfjklsdfklgjdsfkljglkdmfj', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupinvite',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 14, 16, 4, 42, 693232, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='media',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 12, 22, 4, 42, 691469, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='previewlink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 12, 22, 4, 42, 693520, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Key',
        ),
    ]
