# Generated by Django 5.2.1 on 2025-05-15 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_media_key_alter_groupinvite_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinvite',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 15, 7, 20, 747422, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='media',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 15, 21, 7, 20, 745652, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='previewlink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 15, 21, 7, 20, 747754, tzinfo=datetime.timezone.utc)),
        ),
    ]
