# Generated by Django 5.2.1 on 2025-05-15 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_groupinvite_expires_at_alter_media_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupinvite',
            name='invite_token',
        ),
        migrations.AddField(
            model_name='groupinvite',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='groupinvite',
            name='token',
            field=models.CharField(default='lkjmkjmuimiu', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupinvite',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 15, 39, 18, 362029, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='media',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 15, 21, 39, 18, 360257, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='previewlink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 15, 21, 39, 18, 362338, tzinfo=datetime.timezone.utc)),
        ),
    ]
