# Generated by Django 5.2.1 on 2025-05-19 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_groupinvite_expires_at_alter_media_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupinvite',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='previewlink',
            name='enabled',
        ),
        migrations.AlterField(
            model_name='groupinvite',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 17, 33, 12, 971173, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='media',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 19, 23, 33, 12, 969371, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='previewlink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 19, 23, 33, 12, 971500, tzinfo=datetime.timezone.utc)),
        ),
    ]
