# Generated by Django 5.2.1 on 2025-05-19 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_groupinvite_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='previewlink',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='groupinvite',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 17, 58, 41, 235421, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='media',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 19, 23, 58, 41, 233665, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='previewlink',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 19, 23, 58, 41, 235701, tzinfo=datetime.timezone.utc)),
        ),
    ]
